"""Generate paper numbers from complete admitted illustrative comparisons."""
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('rsi_chi_7_5', 'rsi_chi_1_5')
KEYS = ('sigma_0_90', 'sigma_1_00', 'sigma_1_10', 'sigma_1_50')


def read(path):
    return json.loads(path.read_text(encoding='utf-8'))


def admitted_data(name):
    folder = ROOT/'numerical_rewrite'/name
    spec = read(folder/'scenario.json')
    summary = read(folder/'summary.json')
    annual = read(folder/'annual_moments.json')
    event = read(folder/'activation_audit.json')
    manifest = read(folder/'paths_manifest.json')
    figures = read(folder/'figure_manifest.json')
    digest = hashlib.sha256((folder/'equilibrium_paths.csv').read_bytes()).hexdigest()
    reports = [read(folder/f'{k}_audit.json') for k in KEYS]
    if (spec['status'] != 'numerically_admitted' or not event['passes']
            or summary['data_sha256'] != digest or manifest['csv_sha256'] != digest
            or figures['data_sha256'] != digest
            or not annual['outcomes_not_targets']
            or any(r['status'] != 'numerically_admitted'
                   or not r['early_window_checks']['passes'] for r in reports)):
        raise ValueError('Only complete, admitted, current comparisons can enter the paper.')
    return dict(folder=folder, spec=spec, summary=summary, annual=annual,
                event=event, manifest=manifest, figures=figures, reports=reports)


def percent(x, digits=2):
    return f'{100*x:.{digits}f}'+r'\%'


def upper_scientific(x):
    if x == 0:
        return '$0$'
    exponent = math.floor(math.log10(x))
    mantissa = math.ceil(x/10**exponent*100)/100
    return f'${mantissa:.2f}'+r'\times10^{'+str(exponent)+'}$'


def write_reports():
    data = [admitted_data(name) for name in NAMES]
    for name, d in zip(NAMES, data):
        s = d['summary']['scenarios']
        initial = [s[k]['snapshots']['0.0'] for k in KEYS]
        growth = ', '.join('$'+percent(row['output_per_person_growth'])+'$' for row in initial)
        ai = initial[-1]
        annual = d['annual']['scenarios']['sigma_1_00']['first_year']['share']
        price_fall = 1-s['sigma_1_00']['target_window_price_ratio']
        t50 = d['summary']['sigma_1_50_transition_dates']['T50']
        final = s['sigma_1_50']['snapshots']['500.0']
        limits = d['figures']['analytical_limits']['sigma_1_50']
        text = ('% Generated by scripts/report_rewrite_illustrative_rsi.py; do not edit numbers.\n'
            r'Immediately after activation, output-per-person growth is '+growth+
            r' for $\sigma=0.90,1,1.10,1.50$, respectively, compared with $1\%$ before activation.'
            '\nThese are changes in growth rates, not jumps in output levels.\n\n'
            r'At $\sigma=1.50$, initial research expenditure is $'+percent(ai['research_output_share'])+
            r'$ of output and developer net profit is $'+percent(ai['profit_output_share'])+
            "$ of output. Labor's income share reaches half its initial value after about "+
            f'{t50:.0f} years. At year 500, output-per-person growth is $'+
            percent(final['output_per_person_growth'])+r'$, wage growth is $'+
            percent(final['wage_growth'])+r'$, and the interest rate is $'+
            percent(final['net_interest'])+'$.\n\n'
            r'The corresponding long-run limits are $'+
            percent(limits['output_effective_labor_growth']+d['spec']['parameters']['labor_productivity_growth'])+
            r'$, $'+percent(limits['wage_growth'])+r'$, and $'+percent(limits['net_interest'])+
            r'$, respectively; these limits are the same in both exercises.'+'\n\n'
            r'At unit elasticity, first-year research expenditure is $'+percent(annual,3)+
            r'$ of output and the AI-service price falls by $'+percent(price_fall,1)+
            r'$ over the first 27 months. Both are outcomes of the exercise, not calibration targets.'+'\n')
        (ROOT/'sections_rewrite'/f'{name}_results.tex').write_text(text, encoding='utf-8')
        (d['folder']/'README.md').write_text(
            f'# Illustrative RSI productivity: chi={d["spec"]["parameters"]["chi"]:g}\n\n'
            '[Paper](../../main_rewrite.tex) · [Replication guide](../../REPLICATION.md)\n\n'
            'Four newly solved equilibria: sigma=0.9, 1, 1.1, 1.5. Only chi differs\n'
            'between the two displayed comparisons. No expenditure or price target\n'
            'is fitted. Each elasticity inherits its pre-RSI fixed-efficiency BGP.\n\n'
            f'Reproduce: `python scripts/simulate_rewrite_illustrative_rsi.py --chi {d["spec"]["parameters"]["chi"]:g}`.\n\n'
            '`scenario.json` records assumptions; `annual_moments.json` records\n'
            'annual outcomes and quadrature/horizon checks. `*_audit.json` and support\n'
            'files test equations, optimality and long-run continuation;\n'
            '`activation_audit.json` tests pre-event equations and continuity.\n'
            '`equilibrium_paths.csv` feeds the figures, with hashes in the manifests.\n'
            'Window figures show years -2 to 10 and 10 to 500. Numerical admission\n'
            'is not an interval-arithmetic proof. Calendar dates are not forecasts.\n', encoding='utf-8')
    lines = [r'\begin{table}[H]', r'\centering',
             r'\caption{Numerical accuracy of the illustrative RSI comparisons}',
             r'\label{tab:rewrite-rsi-illustrative-accuracy}', r'\small',
             r'\begin{tabular}{rrrrrr}', r'\toprule',
             r'$\chi$ & $\sigma$ & Final horizon & Mesh points & Dynamic residual & Horizon change\\',
             r'\midrule']
    for d in data:
        for r in d['reports']:
            checks = r['independent_dated_checks']+r['early_window_checks']['independent_residuals']
            residual = max(c['maximum_ode_residual'] for c in checks)
            gap = r['horizon_comparison']['maximum_common_window_coordinate_change']
            a = r['audit']
            lines.append(f'{r["parameters"]["chi"]:g} & {r["sigma_xl"]:.2f} & '
                         f'{a["horizon"]:,.1f} & {a["nodes"]:,} & '+
                         upper_scientific(residual)+' & '+upper_scientific(gap)+r'\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\par\smallskip',
        r'\begin{minipage}{0.98\textwidth}\footnotesize',
        'Dynamic residuals are the largest independently reconstructed errors across',
        'the full-horizon and dense first-decade checks. Horizon change compares the',
        'last two solutions in detrended logarithmic coordinates over years 0--500.',
        'Error bounds are rounded upward. All eight paths pass the equation,',
        'event-continuity, developer-optimality and long-run-continuation checks.',
        r'The $\sigma=1.50$ cases use the global Hamiltonian-support test and its',
        'analytical continuation bound; the other cases pass the concavity test.',
        r'\end{minipage}', r'\end{table}']
    (ROOT/'sections_rewrite/rsi_illustrative_accuracy.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')


if __name__ == '__main__':
    write_reports()
